CREATE TABLE `autoTraderHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` varchar(64) NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`direction` varchar(8) NOT NULL,
	`entryPrice` varchar(32) NOT NULL,
	`exitPrice` varchar(32),
	`positionSize` varchar(32) NOT NULL,
	`marginUsed` varchar(32) NOT NULL,
	`leverage` int NOT NULL,
	`takeProfit` varchar(32),
	`stopLoss` varchar(32),
	`pnl` varchar(32),
	`outcome` varchar(32) NOT NULL DEFAULT 'open',
	`durationSeconds` int,
	`signalConfidence` int,
	`entryQuality` varchar(8),
	`errorMessage` text,
	`openedAt` timestamp NOT NULL DEFAULT (now()),
	`closedAt` timestamp,
	CONSTRAINT `autoTraderHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `autoTraderSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` varchar(64) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT false,
	`marginPerTrade` int NOT NULL DEFAULT 50,
	`leverage` int NOT NULL DEFAULT 10,
	`maxConcurrent` int NOT NULL DEFAULT 1,
	`maxDailyTrades` int NOT NULL DEFAULT 10,
	`cooldownSeconds` int NOT NULL DEFAULT 60,
	`minConfidence` int NOT NULL DEFAULT 90,
	`exchange` varchar(32) NOT NULL DEFAULT 'hyperliquid',
	`telegramNotify` boolean NOT NULL DEFAULT true,
	`maxDrawdownPct` int NOT NULL DEFAULT 0,
	`excludeSymbols` text,
	`onlySymbols` text,
	`currentStatus` varchar(32) NOT NULL DEFAULT 'idle',
	`currentSymbol` varchar(32),
	`currentDirection` varchar(8),
	`currentEntryPrice` varchar(32),
	`tradesToday` int NOT NULL DEFAULT 0,
	`lastTradeClosedAt` timestamp,
	`dailyPnl` varchar(32) DEFAULT '0',
	`totalPnl` varchar(32) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `autoTraderSettings_id` PRIMARY KEY(`id`)
);
