CREATE TABLE `exchangeHistorySyncState` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`exchange` varchar(16) NOT NULL,
	`sourceAccountHash` varchar(64) NOT NULL,
	`status` enum('never','running','complete','partial','failed') NOT NULL DEFAULT 'never',
	`cursor` text,
	`rowsFetched` int NOT NULL DEFAULT 0,
	`rowsInserted` int NOT NULL DEFAULT 0,
	`eligibleOutcomes` int NOT NULL DEFAULT 0,
	`earliestImportedAtMs` bigint,
	`latestImportedAtMs` bigint,
	`retentionNote` text,
	`lastError` text,
	`lastAttemptAt` timestamp,
	`lastSuccessAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exchangeHistorySyncState_id` PRIMARY KEY(`id`),
	CONSTRAINT `exchangeHistorySyncState_user_exchange_account_unique` UNIQUE(`userId`,`exchange`,`sourceAccountHash`)
);
--> statement-breakpoint
CREATE TABLE `exchangeTradeFills` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`exchange` varchar(16) NOT NULL,
	`sourceAccountHash` varchar(64) NOT NULL,
	`externalFillId` varchar(128) NOT NULL,
	`externalOrderId` varchar(128),
	`symbol` varchar(32) NOT NULL,
	`side` enum('BUY','SELL') NOT NULL,
	`positionSide` varchar(16),
	`positionEffect` enum('OPEN','CLOSE','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
	`price` text NOT NULL,
	`quantity` text NOT NULL,
	`fee` text,
	`feeAsset` varchar(16),
	`realizedPnl` text,
	`executedAtMs` bigint NOT NULL,
	`eligibleForLearning` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `exchangeTradeFills_id` PRIMARY KEY(`id`),
	CONSTRAINT `exchangeTradeFills_user_exchange_account_fill_unique` UNIQUE(`userId`,`exchange`,`sourceAccountHash`,`externalFillId`)
);
