CREATE TABLE `signalCalibrationObservations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` varchar(64) NOT NULL,
	`observationKey` varchar(128) NOT NULL,
	`modelVersion` varchar(64) NOT NULL,
	`symbol` varchar(32) NOT NULL,
	`direction` enum('LONG','SHORT') NOT NULL,
	`timeframe` varchar(16) NOT NULL DEFAULT '5m+1m',
	`evidenceScore` int NOT NULL,
	`technicalScore` int NOT NULL,
	`microstructureScore` int NOT NULL,
	`entryQuality` varchar(8) NOT NULL,
	`directionsAgree` boolean NOT NULL DEFAULT false,
	`executionEligible` boolean NOT NULL DEFAULT false,
	`entryPrice` varchar(32) NOT NULL,
	`takeProfit` varchar(32) NOT NULL,
	`stopLoss` varchar(32) NOT NULL,
	`outcome` enum('pending','hit_tp','hit_sl','expired','ambiguous') NOT NULL DEFAULT 'pending',
	`actualExitPrice` varchar(32),
	`observedAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp NOT NULL,
	`lastCheckedAt` timestamp,
	`checkCount` int NOT NULL DEFAULT 0,
	`outcomeAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `signalCalibrationObservations_id` PRIMARY KEY(`id`),
	CONSTRAINT `signalCalibration_user_observation_unique` UNIQUE(`userId`,`observationKey`)
);
