/**
 * mlEngine.ts
 *
 * Self-Adaptive ML Model (Layer 2)
 *
 * A lightweight gradient-boosted decision tree ensemble implemented in pure TypeScript.
 * No Python or native dependencies required.
 *
 * Architecture:
 *   - Ensemble of shallow decision trees (stumps/depth-3 trees)
 *   - Gradient boosting: each tree corrects the residuals of the previous ensemble
 *   - Binary classification: LONG (1) vs SHORT (0)
 *   - Outputs: direction + confidence score (0-1)
 *
 * Training:
 *   - Uses last 30 days of verified signal outcomes from signalHistory
 *   - Features generated by featureEngine.ts for each historical signal
 *   - Retrains daily via Heartbeat scheduled job
 *   - Model state persisted to database (mlModelState table)
 *
 * Inference:
 *   - predictSignal(features) → { direction, confidence, featureImportance }
 *   - Fast in-memory inference (~1ms per prediction)
 */

import { getDb } from "../db";
import { mlModelState, signalHistory } from "../../drizzle/schema";
import { desc, eq, gte, and, or } from "drizzle-orm";
import { generateFeatures, getFeatureNames, type FeatureVector } from "./featureEngine";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface MLPrediction {
  direction: "LONG" | "SHORT";
  confidence: number; // 0-1
  featureImportance: { feature: string; importance: number }[];
  modelVersion: number;
  trainingSamples: number;
  modelAccuracy: number;
}

interface DecisionNode {
  featureIndex: number;
  threshold: number;
  leftValue: number;   // prediction if feature <= threshold
  rightValue: number;  // prediction if feature > threshold
  leftChild?: DecisionNode;
  rightChild?: DecisionNode;
}

interface TreeModel {
  root: DecisionNode;
  weight: number; // learning rate weight for this tree
}

interface EnsembleModel {
  trees: TreeModel[];
  featureNames: string[];
  bias: number; // initial prediction (log-odds of positive class)
  version: number;
  accuracy: number;
  trainingSamples: number;
  featureImportance: { feature: string; importance: number }[];
}

interface TrainingSample {
  features: number[];
  label: number; // 1 = LONG was correct, 0 = SHORT was correct
}

// ─── Module State ─────────────────────────────────────────────────────────────

let currentModel: EnsembleModel | null = null;
let modelLoadedAt: number = 0;
const MODEL_ID = "signal_direction_v1";
const MODEL_CACHE_TTL = 3600_000; // 1 hour cache

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Predict signal direction and confidence from a feature vector.
 * Returns null if no trained model is available.
 */
const MIN_SAMPLES_FOR_PENALTY = 50; // Don't penalize signals until model has enough training data

export async function predictSignal(features: FeatureVector): Promise<MLPrediction | null> {
  const model = await getModel();
  if (!model || model.trees.length === 0) return null;

  // Convert feature vector to ordered array
  const featureArray = model.featureNames.map(name => features[name] ?? 0);

  // Run inference
  let logOdds = model.bias;
  for (const tree of model.trees) {
    logOdds += tree.weight * evaluateTree(tree.root, featureArray);
  }

  // Sigmoid to get probability
  const probability = sigmoid(logOdds);

  // Direction and confidence
  const direction: "LONG" | "SHORT" = probability >= 0.5 ? "LONG" : "SHORT";
  const confidence = direction === "LONG" ? probability : 1 - probability;

  return {
    direction,
    confidence: parseFloat(confidence.toFixed(4)),
    featureImportance: model.featureImportance.slice(0, 10),
    modelVersion: model.version,
    trainingSamples: model.trainingSamples,
    modelAccuracy: model.accuracy,
  };
}

/**
 * Retrain the model using the last 30 days of verified signal outcomes.
 * Called daily by Heartbeat scheduled job.
 */
export async function retrainModel(): Promise<{
  success: boolean;
  accuracy: number;
  trainingSamples: number;
  version: number;
  message: string;
}> {
  console.log("[ML Engine] Starting model retraining...");

  try {
    // 1. Fetch training data from signalHistory (last 30 days, verified outcomes only)
    const db = await getDb();
    if (!db) throw new Error("Database not available");
    const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);

    const signals = await db
      .select()
      .from(signalHistory)
      .where(
        and(
          gte(signalHistory.generatedAt, thirtyDaysAgo),
          or(
            eq(signalHistory.outcome, "hit_tp"),
            eq(signalHistory.outcome, "hit_sl")
          )
        )
      )
      .orderBy(desc(signalHistory.generatedAt))
      .limit(500);

    if (signals.length < 10) {
      console.log(`[ML Engine] Insufficient training data: ${signals.length} samples (need >= 10)`);
      return {
        success: false,
        accuracy: 0,
        trainingSamples: signals.length,
        version: currentModel?.version ?? 0,
        message: `Insufficient training data: ${signals.length} samples (minimum 10 required)`,
      };
    }

    console.log(`[ML Engine] Found ${signals.length} verified signals for training`);

    // 2. Build training samples
    // Label: 1 if the signal direction was correct (hit_tp), 0 if wrong (hit_sl)
    const featureNames = getFeatureNames();
    const trainingSamples: TrainingSample[] = [];

    for (const signal of signals) {
      // Parse metadata for stored features (if available)
      let features: number[] | null = null;

      if (signal.metadata) {
        try {
          const meta = JSON.parse(signal.metadata);
          if (meta.mlFeatures && Array.isArray(meta.mlFeatures)) {
            features = meta.mlFeatures;
          }
        } catch { /* ignore parse errors */ }
      }

      // If no stored features, generate synthetic features from signal data
      if (!features) {
        features = generateSyntheticFeatures(signal, featureNames);
      }

      // Label: 1 = direction was correct (hit TP), 0 = direction was wrong (hit SL)
      const label = signal.outcome === "hit_tp" ? 1 : 0;
      trainingSamples.push({ features, label });
    }

    // 3. Split into train/validation (80/20)
    const shuffled = [...trainingSamples].sort(() => Math.random() - 0.5);
    const splitIdx = Math.floor(shuffled.length * 0.8);
    const trainSet = shuffled.slice(0, splitIdx);
    const valSet = shuffled.slice(splitIdx);

    console.log(`[ML Engine] Training: ${trainSet.length} samples, Validation: ${valSet.length} samples`);

    // 4. Train gradient boosted ensemble
    const numTrees = Math.min(50, Math.max(10, Math.floor(trainSet.length / 5)));
    const learningRate = 0.1;
    const maxDepth = 3;

    const model = trainGradientBoostedEnsemble(
      trainSet,
      featureNames,
      numTrees,
      learningRate,
      maxDepth
    );

    // 5. Evaluate on validation set
    let correct = 0;
    for (const sample of valSet) {
      let logOdds = model.bias;
      for (const tree of model.trees) {
        logOdds += tree.weight * evaluateTree(tree.root, sample.features);
      }
      const pred = sigmoid(logOdds) >= 0.5 ? 1 : 0;
      if (pred === sample.label) correct++;
    }
    const accuracy = valSet.length > 0 ? Math.round((correct / valSet.length) * 100) : 0;

    // 6. Compute feature importance
    const importance = computeFeatureImportance(model.trees, featureNames);

    // 7. Get next version number
    const prevModel = await db!
      .select({ version: mlModelState.version })
      .from(mlModelState)
      .where(eq(mlModelState.modelId, MODEL_ID))
      .orderBy(desc(mlModelState.version))
      .limit(1);
    const nextVersion = (prevModel[0]?.version ?? 0) + 1;

    // 8. Persist model to database
    const ensembleModel: EnsembleModel = {
      trees: model.trees,
      featureNames,
      bias: model.bias,
      version: nextVersion,
      accuracy,
      trainingSamples: trainingSamples.length,
      featureImportance: importance,
    };

    await db!.insert(mlModelState).values({
      modelId: MODEL_ID,
      modelData: JSON.stringify({ trees: model.trees, bias: model.bias }),
      accuracy,
      trainingSamples: trainingSamples.length,
      featureImportance: JSON.stringify(importance),
      trainingWindowStart: thirtyDaysAgo,
      trainingWindowEnd: new Date(),
      version: nextVersion,
    });

    // 9. Update in-memory model
    currentModel = ensembleModel;
    modelLoadedAt = Date.now();

    console.log(`[ML Engine] Retraining complete: v${nextVersion}, accuracy=${accuracy}%, samples=${trainingSamples.length}, trees=${numTrees}`);

    return {
      success: true,
      accuracy,
      trainingSamples: trainingSamples.length,
      version: nextVersion,
      message: `Model v${nextVersion} trained successfully. Accuracy: ${accuracy}% on ${valSet.length} validation samples.`,
    };
  } catch (error: any) {
    console.error("[ML Engine] Retraining failed:", error.message);
    return {
      success: false,
      accuracy: 0,
      trainingSamples: 0,
      version: currentModel?.version ?? 0,
      message: `Retraining failed: ${error.message}`,
    };
  }
}

/**
 * Get current model status for monitoring UI.
 */
export async function getModelStatus(): Promise<{
  loaded: boolean;
  version: number;
  accuracy: number;
  trainingSamples: number;
  lastTrainedAt: string | null;
  featureImportance: { feature: string; importance: number }[];
}> {
  const model = await getModel();
  if (!model) {
    return {
      loaded: false,
      version: 0,
      accuracy: 0,
      trainingSamples: 0,
      lastTrainedAt: null,
      featureImportance: [],
    };
  }
  return {
    loaded: true,
    version: model.version,
    accuracy: model.accuracy,
    trainingSamples: model.trainingSamples,
    lastTrainedAt: new Date(modelLoadedAt).toISOString(),
    featureImportance: model.featureImportance.slice(0, 15),
  };
}

// ─── Model Loading ────────────────────────────────────────────────────────────

async function getModel(): Promise<EnsembleModel | null> {
  // Return cached model if fresh
  if (currentModel && Date.now() - modelLoadedAt < MODEL_CACHE_TTL) {
    return currentModel;
  }

  // Load latest model from database
  try {
    const db = await getDb();
    if (!db) return null;
    const rows = await db
      .select()
      .from(mlModelState)
      .where(eq(mlModelState.modelId, MODEL_ID))
      .orderBy(desc(mlModelState.version))
      .limit(1);

    if (rows.length === 0) return null;

    const row = rows[0];
    const parsed = JSON.parse(row.modelData);
    const importance = row.featureImportance ? JSON.parse(row.featureImportance) : [];

    currentModel = {
      trees: parsed.trees ?? [],
      featureNames: getFeatureNames(),
      bias: parsed.bias ?? 0,
      version: row.version,
      accuracy: row.accuracy,
      trainingSamples: row.trainingSamples,
      featureImportance: importance,
    };
    modelLoadedAt = Date.now();
    return currentModel;
  } catch (error: any) {
    console.error("[ML Engine] Failed to load model:", error.message);
    return null;
  }
}

// ─── Gradient Boosted Ensemble Training ───────────────────────────────────────

function trainGradientBoostedEnsemble(
  samples: TrainingSample[],
  featureNames: string[],
  numTrees: number,
  learningRate: number,
  maxDepth: number
): { trees: TreeModel[]; bias: number } {
  const n = samples.length;

  // Initial prediction: log-odds of positive class
  const posCount = samples.filter(s => s.label === 1).length;
  const bias = Math.log((posCount + 1) / (n - posCount + 1));

  // Current predictions (log-odds)
  const predictions = new Array(n).fill(bias);
  const trees: TreeModel[] = [];

  for (let t = 0; t < numTrees; t++) {
    // Compute residuals (negative gradient of log-loss)
    const residuals = samples.map((s, i) => {
      const p = sigmoid(predictions[i]);
      return s.label - p; // gradient of binary cross-entropy
    });

    // Fit a regression tree to residuals
    const tree = fitRegressionTree(samples, residuals, featureNames.length, maxDepth);
    if (!tree) continue;

    // Update predictions
    for (let i = 0; i < n; i++) {
      const leafValue = evaluateTree(tree, samples[i].features);
      predictions[i] += learningRate * leafValue;
    }

    trees.push({ root: tree, weight: learningRate });
  }

  return { trees, bias };
}

function fitRegressionTree(
  samples: TrainingSample[],
  residuals: number[],
  numFeatures: number,
  maxDepth: number
): DecisionNode | null {
  if (samples.length < 4) return null;

  return buildTreeNode(
    samples.map((s, i) => ({ features: s.features, residual: residuals[i] })),
    numFeatures,
    maxDepth,
    0
  );
}

function buildTreeNode(
  data: { features: number[]; residual: number }[],
  numFeatures: number,
  maxDepth: number,
  depth: number
): DecisionNode {
  const meanResidual = data.reduce((s, d) => s + d.residual, 0) / data.length;

  // Leaf node conditions
  if (depth >= maxDepth || data.length < 8) {
    return {
      featureIndex: 0,
      threshold: 0,
      leftValue: meanResidual,
      rightValue: meanResidual,
    };
  }

  // Find best split
  let bestGain = -Infinity;
  let bestFeature = 0;
  let bestThreshold = 0;
  let bestLeftData: typeof data = [];
  let bestRightData: typeof data = [];

  // Sample features for split (random subset for speed)
  const featureSubset = sampleFeatureIndices(numFeatures, Math.min(numFeatures, Math.ceil(Math.sqrt(numFeatures))));

  for (const fi of featureSubset) {
    // Get unique values for this feature
    const values = Array.from(new Set(data.map(d => d.features[fi]))).sort((a, b) => a - b);
    if (values.length < 2) continue;

    // Try midpoints as thresholds (sample up to 10 for speed)
    const step = Math.max(1, Math.floor(values.length / 10));
    for (let vi = 0; vi < values.length - 1; vi += step) {
      const threshold = (values[vi] + values[vi + 1]) / 2;

      const leftData = data.filter(d => d.features[fi] <= threshold);
      const rightData = data.filter(d => d.features[fi] > threshold);

      if (leftData.length < 3 || rightData.length < 3) continue;

      // Compute gain (reduction in variance of residuals)
      const leftMean = leftData.reduce((s, d) => s + d.residual, 0) / leftData.length;
      const rightMean = rightData.reduce((s, d) => s + d.residual, 0) / rightData.length;

      const totalVar = data.reduce((s, d) => s + (d.residual - meanResidual) ** 2, 0);
      const leftVar = leftData.reduce((s, d) => s + (d.residual - leftMean) ** 2, 0);
      const rightVar = rightData.reduce((s, d) => s + (d.residual - rightMean) ** 2, 0);

      const gain = totalVar - leftVar - rightVar;
      if (gain > bestGain) {
        bestGain = gain;
        bestFeature = fi;
        bestThreshold = threshold;
        bestLeftData = leftData;
        bestRightData = rightData;
      }
    }
  }

  // If no good split found, return leaf
  if (bestGain <= 0 || bestLeftData.length === 0 || bestRightData.length === 0) {
    return {
      featureIndex: 0,
      threshold: 0,
      leftValue: meanResidual,
      rightValue: meanResidual,
    };
  }

  // Recurse
  const leftChild = buildTreeNode(bestLeftData, numFeatures, maxDepth, depth + 1);
  const rightChild = buildTreeNode(bestRightData, numFeatures, maxDepth, depth + 1);

  return {
    featureIndex: bestFeature,
    threshold: bestThreshold,
    leftValue: bestLeftData.reduce((s, d) => s + d.residual, 0) / bestLeftData.length,
    rightValue: bestRightData.reduce((s, d) => s + d.residual, 0) / bestRightData.length,
    leftChild,
    rightChild,
  };
}

function evaluateTree(node: DecisionNode, features: number[]): number {
  if (features[node.featureIndex] <= node.threshold) {
    return node.leftChild ? evaluateTree(node.leftChild, features) : node.leftValue;
  } else {
    return node.rightChild ? evaluateTree(node.rightChild, features) : node.rightValue;
  }
}

function sigmoid(x: number): number {
  if (x > 20) return 1;
  if (x < -20) return 0;
  return 1 / (1 + Math.exp(-x));
}

function sampleFeatureIndices(total: number, count: number): number[] {
  const indices = Array.from({ length: total }, (_, i) => i);
  // Fisher-Yates shuffle and take first `count`
  for (let i = indices.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [indices[i], indices[j]] = [indices[j], indices[i]];
  }
  return indices.slice(0, count);
}

// ─── Feature Importance ───────────────────────────────────────────────────────

function computeFeatureImportance(
  trees: TreeModel[],
  featureNames: string[]
): { feature: string; importance: number }[] {
  const importance = new Array(featureNames.length).fill(0);

  for (const tree of trees) {
    accumulateImportance(tree.root, importance, tree.weight);
  }

  // Normalize
  const total = importance.reduce((s, v) => s + v, 0) || 1;
  const normalized = importance.map((v, i) => ({
    feature: featureNames[i] ?? `feature_${i}`,
    importance: parseFloat((v / total).toFixed(4)),
  }));

  // Sort by importance descending
  normalized.sort((a, b) => b.importance - a.importance);
  return normalized.filter(f => f.importance > 0);
}

function accumulateImportance(node: DecisionNode, importance: number[], weight: number): void {
  if (!node.leftChild && !node.rightChild) return; // leaf
  if (node.featureIndex < importance.length) {
    importance[node.featureIndex] += weight;
  }
  if (node.leftChild) accumulateImportance(node.leftChild, importance, weight);
  if (node.rightChild) accumulateImportance(node.rightChild, importance, weight);
}

// ─── Synthetic Feature Generation ─────────────────────────────────────────────

/**
 * Generate approximate features from a historical signal's metadata.
 * Used when we don't have stored ML features for older signals.
 */
function generateSyntheticFeatures(signal: any, featureNames: string[]): number[] {
  const features = new Array(featureNames.length).fill(0);

  // Use available signal data to populate key features
  const confidence = signal.confidence ?? 50;
  const direction = signal.direction === "LONG" ? 1 : 0;

  // Parse metadata if available
  let meta: any = {};
  if (signal.metadata) {
    try { meta = JSON.parse(signal.metadata); } catch { /* ignore */ }
  }

  // Populate features based on what we know
  for (let i = 0; i < featureNames.length; i++) {
    const name = featureNames[i];

    // RSI features — estimate from confidence and direction
    if (name.includes("rsi14")) {
      features[i] = direction === 1
        ? 30 + (confidence / 100) * 20 // LONG: RSI 30-50 (oversold)
        : 50 + (confidence / 100) * 20; // SHORT: RSI 50-70 (overbought)
      features[i] += (Math.random() - 0.5) * 10; // Add noise
    }
    // EMA distance — estimate from direction
    else if (name.includes("ema") && name.includes("dist")) {
      features[i] = direction === 1
        ? -0.5 + Math.random() * 1 // LONG: slightly below EMA
        : 0.5 + Math.random() * 1; // SHORT: slightly above EMA
    }
    // BB position
    else if (name.includes("bb_pos")) {
      features[i] = direction === 1
        ? 20 + Math.random() * 30 // LONG: lower half
        : 50 + Math.random() * 30; // SHORT: upper half
    }
    // ADX — add randomized strength
    else if (name.includes("adx")) {
      features[i] = 20 + Math.random() * 30;
    }
    // Stochastic
    else if (name.includes("stoch_k")) {
      features[i] = direction === 1 ? 20 + Math.random() * 30 : 50 + Math.random() * 30;
    }
    // MFI
    else if (name.includes("mfi")) {
      features[i] = direction === 1 ? 30 + Math.random() * 20 : 50 + Math.random() * 20;
    }
    // Volume ratio
    else if (name.includes("vol_ratio")) {
      features[i] = 0.8 + Math.random() * 1.5;
    }
    // MACD
    else if (name.includes("macd")) {
      features[i] = direction === 1 ? Math.random() * 0.1 : -Math.random() * 0.1;
    }
    // ATR
    else if (name.includes("atr_pct")) {
      features[i] = 0.5 + Math.random() * 2;
    }
    // OBV slope
    else if (name.includes("obv_slope")) {
      features[i] = direction === 1 ? Math.random() * 0.5 : -Math.random() * 0.5;
    }
    // BTC correlation
    else if (name === "btc_correlation_20") {
      features[i] = 0.3 + Math.random() * 0.5;
    }
    // Default: small random noise
    else {
      features[i] = (Math.random() - 0.5) * 2;
    }
  }

  return features;
}
